name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "iOS_14.2"
  comment: "Software"
  url: http://updates-http.cdn-apple.com/2020FallFCS/fullrestores/001-74652/EE41A4BE-D95B-4A2D-A734-F8ACAC1C61AA/iPhone10,3,iPhone10,6_14.2_18B92_Restore.ipsw
  file_name: "iPhone10,3,iPhone10,6_14.2_18B92_Restore.ipsw"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
