name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "iP7P-iOS14"
  comment: "iOS"
  url: https://api.ipsw.me/v4/ipsw/download/iPhone9,4/18A373
  file_name: "iP7P-iOS14.ipsw"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
